name: PHP

on:
  workflow_dispatch:
#  schedule:
 #   - cron: '5,15,25,35,45,55 * * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.29.0-focal
    strategy:
      matrix:
        version: [10, 12, 14, 16, 18, 20, 22, 24]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.KEY }}

    - name: First
      run: pip install pytest-playwright
    - name: Second
      run: playwright install
    - name: Run 
      run: pytest test.py
      
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updating Files
#        branch: Auto-Commit-Branch
        push_options: --force
